apiVersion: v1
kind: Template
labels:
  template: approval-api-secrets
metadata:
  name: approval-api-secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: approval-api-secrets
    labels:
      app: approval
  stringData:
    secret-key: "${SECRET_KEY}"
parameters:
- name: SECRET_KEY
  displayName: Secret Key
  required: true
  description: Rails SECRET_KEY_BASE
  from: "[a-f0-9]{128}"
  generate: expression
